version: '3.8'
services:
  app:
    build:
      context: ./infra/app
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html/backend
      - yosan-vscode-extensions:/root/.vscode-server/extensions
      - yosan-back-node_modules:/var/www/html/backend/node_modules
  db:
    build:
      context: ./infra/db
    environment:
      MYSQL_DATABASE: yosan_db
      MYSQL_USER: Amori
      MYSQL_PASSWORD: Amori0402
      MYSQL_ROOT_PASSWORD: Amori0402
    ports:
      - 3306:3306
    volumes:
      - ./infra/db/mysql/data:/var/lib/mysql
  adminer:
    image: adminer:4.8.1
    ports:
      - 8001:8080
    depends_on:
      - db

volumes:
  yosan-vscode-extensions:
  yosan-back-node_modules:
